version: '3.8'

services:
  infinity-bot:
    build: .
    container_name: infinity_plus
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./resources:/app/resources
      - ./infinity_plus_config.json:/app/infinity_plus_config.json