name: 🧹 Massive Cleanup

on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: 🗑️ Delete all workflow runs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          REPO=${{ github.repository }}
          
          echo "Starting cleanup for $REPO..."
          gh run list --repo $REPO --limit 1000 --json databaseId -q '.[].databaseId' | xargs -I{} gh run delete --repo $REPO {}
          
          echo "✅ All logs have been wiped out!"
